# Actual dates of the viz frames
vizDates:
  start: '2022-04-01'
  end: '2022-06-30'

# view, dimensions
bbox: [-130.0, 20.0, -77.0, 49.0]
projection: "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs "
height: 2048
width: 4096

# fetch site data parameters
request_limit: 10
request_limit_historic: 5
request_limit_inst: 1
percentiles:
  calc: ["05","10","20","25","50","75","80","90","95"]
  display:
    drought_severe: "05"
    drought_low: "10"
    normal_range: ["25", "75"]
    wet: "90"

# styling
gage_style:
  with_percentile:
    normal:
      pch: 21
      cex: 2.0
      bg: "#d7d7d7" #efefef
    drought:
      pch: 21
      cex: [2.0, 3.0, 5.0]
      col: ["#efb2bc", "#df6679", "#ca0020"]
      lwd: 2.0
    wet:
      pch: 21
      cex: 2.0
      bg: ["#92c5de", "#04507d"]
    flood:    # not based on percentile, based on if above flood stage or not
      pch: 21
      cex: 4.0
      lwd: 5.0
      bg: "#04507d" # same as second "wet"
      col: "#AE72E5" #"#9547dd"
  no_percentile:
    pch: 4
    cex: 1.5
    col: "#7f7f7f"

